id: I007B3303
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T02:35:58+00:00'
last_modified: '2022-06-08T13:29:32.987211+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105855
  title: གངས་འདབ་ཀྱི་རེ་སྨོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5688':
      image_group_id: I1PD105857
      title: ''
      total_pages: 2
      order: 1
      base_file: 5688.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
