id: P010422
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:49:06.002594
source_metadata:
  id: bdr:W1PD105855
  title: གངས་འདབ་ཀྱི་རེ་སྨོན།
  author: ''
  volumes:
    9a1088e54d354b79aad398caae154996:
      image_group_id: I1PD105857
      title: ''
      volume_number: 1
      total_pages: 2
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
